= Russian Phonetic Encoder
Nikolay Papakha
:toc:
:toc-placement!:
:!toc-title:
:toclevels: 4
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :paperclip:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
ifndef::env-github[]
endif::[]

Russian Phonetic encoder accepts the word with Russian characters in `*а-я*` range and produces a phonetic code.

:url-throughput-benchmark: https://github.com/papahigh/elasticsearch-russian-phonetics/blob/master/benchmark/throughput.asciidoc
:url-distribution-benchmark: https://github.com/papahigh/elasticsearch-russian-phonetics/blob/master/benchmark/distribution.asciidoc

toc::[]

== Character set

The character set used in the resulting code depends on provided `*vowels*` encoding mode:

* 21 symbols are used with `*ignore*` vowels encoding mode
+
`*б*`, `*в*`, `*г*`, `*д*`, `*ж*`, `*з*`, `*й*`, `*к*`, `*л*`, `*м*`, `*н*`, `*п*`, `*р*`, `*с*`, `*т*`, `*ф*`, `*х*`, `*ц*`, `*ч*`, `*ш*`, `*щ*`
* 26 symbols are used with `*encode_first*` vowels encoding mode
+
`*б*`, `*в*`, `*г*`, `*д*`, `*ж*`, `*з*`, `*й*`, `*к*`, `*л*`, `*м*`, `*н*`, `*п*`, `*р*`, `*с*`, `*т*`, `*ф*`, `*х*`, `*ц*`, `*ч*`, `*ш*`, `*щ*`
+
plus `*а*`, `*э*`, `*у*`, `*ю*`, `*я*` for the first vowel
* 29 symbols are used with `*encode_all*` vowels encoding mode
+
`*б*`, `*в*`, `*г*`, `*д*`, `*ж*`, `*з*`, `*й*`, `*к*`, `*л*`, `*м*`, `*н*`, `*п*`, `*р*`, `*с*`, `*т*`, `*ф*`, `*х*`, `*ц*`, `*ч*`, `*ш*`, `*щ*`
+
plus `*а*`, `*э*`, `*у*`, `*ю*`, `*я*` for the first and `*1*`, `*2*`, `*3*` for the rest vowels of the supplied word

== Maximum length
Russian Phonetic encoder gives the following guarantee on maximum length of the resulting code:

* it won't be longer than specified `*max_code_len*` value
* if stemming analysis was supplied along with `*max_code_len*` then encoder gives additional
guarantee that generated code also won't be longer than `StemmedLengthOfTheSuppliedWord - NumberOfDroppedCharacters`

TIP: Please take a look at the {url-throughput-benchmark}[throughput] and {url-distribution-benchmark}[distribution] benchmarks to be aware of encoder's
behaviour and performance under certain options value.

== Encoding rules

Encoding happens by applying the following rules:

. convert to lowercase

. [[rule-2]]drop duplicate adjacent letters and anything not `*а-я*`

. [[first-vowel-mapping]]if first letter in the word is vowel then:
+
`*а*`, `*о*` → `*а*`
+
`*э*`, `*е*`, `*ы*`, `*и*`, `*ё*` → `*э*`
+
`*у*` → `*у*`
+
`*ю*` → `*ю*`
+
`*я*` → `*я*`

. if the word starts with `*й*` or `*и*` followed by a vowel then:
+
`*йу*`, `*иу*` → `*ю*`
+
`*йа*`, `*иа*` → `*я*`
+
`*йо*`, `*ио*` → `*э*`
+
else drop the first letter and apply link:#first-vowel-mapping[*rule 3*] for the second vowel

. transform any vowel, except `*у*`, `*ю*`, after `*ж*`, `*ц*`, `*ш*`, `*ч*` or `*щ*` → `*2*`

. `*я*` after `*б*`, `*в*`, `*г*`, `*д*`, `*з*`, `*к*`, `*л*`, `*м*`, `*н*`, `*п*`, `*р*`, `*с*`, `*т*`, `*ф*`, `*х*` transforms to `*2*`. Otherwise, `*я*` transforms to `*1*`

. in order to keep consistency with link:#rule-2[*rule 2*], reduce the following sequences of vowels having near-similar sound:
+
`*ао*` `*оа*` `*оо*` `*аа*` → `*1*`
+
____
в**оо**бражение ⟷ в**оа**бражение

кл**аа**ка ⟷ кл**оа**ка

к**оо**лиция ⟷ к**оа**лиция

п**оо**бещать ⟷ п**оа**бещать
____
+
`*э*`, `*е*`, `*ы*`, `*и*` followed by `*э*`, `*е*`, `*ы*`, `*и*` → `*2*`
+
`*а*`, `*я*` after `*ж*`, `*ц*`, `*ш*`, `*ч*`, `*щ*` and followed by `*э*`, `*е*`, `*ы*`, `*и*` → `*2*`
+
____
хокк**ии**ст ⟷ хок**еи**ст

ч**ии**нка ⟷ ч**аи**нка

ч**ии**нка ⟷ ч**яи**нка

н**ии**стовый ⟷ н**еи**стовый

ассоц**ии**ровать ⟷ ассоц**еи**ровать

ассоц**ии**ровать ⟷ ассоц**ыи**ровать

пер**ии**начить ⟷ пер**еи**начить

нукл**ии**новый ⟷ нукл**еи**новый

нукл**ии**новый ⟷ нукл**еи**новый

пац**ие**нт ⟷ пац**ые**нт

ит**ы**ровский ⟷ ит**эе**ровский footnoteref:[itr,ИТР - инженерно­-технический работник.]

ит**э**ровский ⟷ ит**эе**ровский footnoteref:[itr]
____

. drop `*й*`, `*и*`, `*е*`, `*ы*` if before vowel and not dropped already

. if none of above matched for a vowel then:
+
`*а*`, `*я*`, `*о*`, `*ё*` → `*1*`
+
`*э*`, `*е*`, `*ы*`, `*и*` → `*2*`
+
`*у*`, `*ю*`       → `*3*`

. drop `*ь*` and `*ъ*`

. `*г*` transforms to `*в*` in `*ого*`, `*его*` at the end of the word

. reduce the following sequences of consonants:
+
`*вств*` → `*ств*`
+
____
здра**вств**уй → здра**ств**уй
____
+
`*гк*` → `*хк*`
+
____
мя**гк**ий → мя**хк**ий
____
+
`*дч*`, `*тч*` → `*ч*`
+
____
прохо**дч**ик → прохо**ч**ик
____
+
`*дц*`, `*дс*`, `*тц*`, `*дц*`, `*тс*`, `*тьс*` → `*ц*`
+
____
инохо**дц**ы → инохо**ц**ы
____
+
`*дск*`, `*тск*` → `*цк*`
+
____
кислово**дск** → кислово**цк**
____
+
`*жк*` → `*шк*`
+
____
впереме**жк**у → впереме**шк**у
____
+
`*зс*` → `*с*`
+
____
ра**зс**ылать → ра**с**ылать
____
+
`*зч*`, `*сч*`, `*сщ*`, `*шч*`, `*жч*`, `*здч*`, `*стч*`, `*тщ*` → `*щ*`
+
____
перебе**жч**ик → перебе**щ**ик
____
+
`*здц*`, `*стц*` → `*сц*`
+
____
кре**стц**овый → кре**сц**овый
____
+
`*здн*` → `*зн*`
+
____
звё**здн**ый → звё**зн**ый
____
+
`*зтг*`, `*стг*` → `*зг*`
+
____
бю**стг**алтер → бю**зг**алтер
____
+
`*лнц*`, `*ндц*` → `*нц*`
+
____
голла**ндц**ы → голла**нц**ы
____
+
`*ндк*` → `*нк*`
+
____
ирла**ндк**а → ирла**нк**а
____
+
`*ндск*` → `*нск*`
+
____
голла**ндск**ий → голла**нск**ий
____
+
`*ндш*`, `*нтш*` → `*нш*`
+
____
ла**ндш**афт → ла**нш**афт
____
+
`*нтг*` → `*нг*`
+
____
ре**нтг**ен → ре**нг**ен
____
+
`*нтк*` → `*нк*`
+
____
студе**нтк**а → студе**нк**а
____
+
`*нтск*` → `*нск*`
+
____
гига**нтск**ий → гига**нск**ий
____
+
`*нтств*` → `*нств*`
+
____
аге**нтств**о → аге**нств**о
____
+
`*рдц*` → `*рц*`
+
____
се**рдц**е → се**рц**е
____
+
`*рдч*` → `*рч*`
+
____
се**рдч**ишко → се**рч**ишко
____
+
`*сж*`, `*зж*` → `*ж*`
+
____
уе**зж**ать → уе**ж**ать
____
+
`*сз*` → `*з*`
+
____
бю**сзг**алтер → бю**зг**алтер
____
+
`*сш*`, `*зш*` → `*ш*`
+
____
вы**сш**ий → вы**ш**ий
____
+
`*стк*`, `*сдк*`, `*зтк*`, `*здк*` → `*ск*`
+
____
машини**стк**а → машини**ск**а
____
+
`*стг*`, `*сдг*`, `*зтг*`, `*здг*` → `*зг*`
+
____
бю**стг**алтер → бю**зг**алтер
____
+
`*стл*` → `*сл*`
+
____
сча**стл**ивый → сча**сл**ивый
____
+
`*стн*` → `*сн*`
+
____
ле**стн**ица → ле**сн**ица
____
+
`*стск*` → `*ск*`
+
____
маркси**стск**ий → маркси**ск**ий
____
+
`*хг*` → `*г*`
+
____
бу**хг**алтер → бу**г**алтер
____
+
`*чн*` → `*шн*`
+
____
коне**чн**о → коне**шн**о
____
+
`**чт**` → `**шт**`
+
____
**чт**о → **шт**о
____

. apply voicing rules for paired consonants `*б*`, `*п*`, `*з*`, `*с*`, `*д*`, `*т*`, `*в*`, `*ф*`, `*г*`, `*к*`, `*ж*`, `*ш*`:
+
voiced consonant transforms to unvoiced at the end of the word
+
____
моти**в** → моти**ф**

а**б**сур**д** → а**п**сур**т**
____
+
if the word ends with double voiced consonants then both transform to unvoiced
+
____
вдры**зг** → вдры**ск**

ви**зг** → ви**ск**

гро**здь** → гро**сть**
____
+
voiced consonant transforms to unvoiced if followed by unvoiced
+
____
а**вт**омат → а**фт**омат
____
+
unvoiced consonant transforms to voiced if followed by voiced, except `*в*`
+
____
моло**тьб**а → моло**дьб**а

чувс**тв**о → чус**тв**о
____

